import type { StandardClauseItem } from "./types";

/** Standard protections in an Indian freelance or independent-contractor service agreement. */
export const FREELANCE_SERVICE_AGREEMENT_ITEMS: readonly StandardClauseItem[] = [
  {
    id: "scope_of_work",
    topic: "Scope of work and deliverables",
    explanation:
      "The agreement does not appear to describe the work to be delivered. A written scope is the reference point " +
      "for what the fee covers and what counts as extra work.",
    presence: [
      "scope",
      "deliverable",
      "statement of work",
      "sow",
      "service",
      "specification",
      "work order",
      "purchase order",
      "brief",
      "milestone",
    ],
    topicKeywords: [["scope of work"], ["scope of service"], ["undefined scope"]],
  },
  {
    id: "payment_timeline",
    topic: "When payment is due",
    explanation:
      "The agreement does not appear to say when payments are due, for example within a set number of days of an " +
      "invoice or on each milestone. A due date is what makes a payment late.",
    presence: [
      "due date",
      "due on",
      "due within",
      "due upon",
      "payable within",
      "payable on",
      "payable upon",
      "payable by",
      "paid within",
      "paid on",
      "paid upon",
      "paid by",
      "payment within",
      "payment on",
      "payment upon",
      "payment shall be made",
      "payment will be made",
      "on or before",
      "in advance",
      "advance payment",
      "upfront",
      "up front",
      "net 30",
      "30 days of",
      "30 days from",
      "30 days after",
      "30 days following",
      "days of receipt",
      "days from receipt",
      "days of invoice",
      "milestone",
      "instalment",
      "installment",
      "on completion",
      "upon completion",
      "on delivery",
      "upon delivery",
      "on acceptance",
      "upon acceptance",
      "monthly",
      "every month",
      "each month",
      "weekly",
      "fortnightly",
    ],
    topicKeywords: [
      ["payment timeline"],
      ["payment schedule"],
      ["payment due date"],
      ["when payment is due"],
      ["when", "will be paid"],
    ],
  },
  {
    id: "late_payment",
    topic: "Late payment interest or charges",
    explanation:
      "The agreement does not appear to provide for interest or charges if payment is late. Separately, a supplier " +
      "registered as a micro or small enterprise may have a statutory right to interest on delayed payments under " +
      "the MSMED Act, 2006.",
    presence: [
      "late payment",
      "late fee",
      "late charge",
      "delayed payment",
      "delay in payment",
      "payment is delayed",
      "payments are delayed",
      "delayed beyond",
      "overdue",
      "past due",
      "outstanding amount",
      "outstanding invoice",
      "interest at",
      "interest of",
      "interest on",
      "interest rate",
      "rate of interest",
      "interest per",
      "per annum",
      "msmed",
      "msme",
      "micro small and medium",
      "penal interest",
      "default interest",
    ],
    topicKeywords: [["late payment"], ["late fee"], ["delayed payment"], ["interest", "late"], ["interest", "delay"]],
  },
  {
    id: "ip_transfer_on_payment",
    topic: "Ownership passing only after payment",
    explanation:
      "The agreement does not appear to link the transfer of ownership of the work to payment. Freelance agreements " +
      "commonly say that rights in the deliverables pass to the client only once the fees are paid in full. Under " +
      "the Copyright Act, 1957, an assignment of copyright is valid only if it is in writing.",
    presence: [
      "full payment",
      "payment in full",
      "paid in full",
      "receipt of payment",
      "receipt of the payment",
      "receipt of full",
      "receipt of the full",
      "receipt of all",
      "receipt of fee",
      "receipt of the fee",
      "subject to payment",
      "subject to receipt",
      "subject to the receipt",
      "until payment",
      "until paid",
      "until the fee",
      "until all fee",
      "until all amount",
      "unless paid",
      "once paid",
      "once payment",
      "once the fee",
      "once all",
      "been paid",
      "has paid",
      "have paid",
      "upon payment",
      "on payment",
      "after payment",
      "clearance of payment",
      "clearance of all",
      "final payment",
      "settlement of all",
    ],
    topicKeywords: [
      ["ownership", "payment"],
      ["intellectual property", "payment"],
      ["ip", "payment"],
      ["copyright", "payment"],
    ],
  },
  {
    id: "revision_limits",
    topic: "Limit on revisions",
    explanation:
      "The agreement does not appear to limit the number of revisions or say how extra changes are charged. Without " +
      "a limit, requests for further changes can continue without additional payment.",
    presence: [
      "revision",
      "revise",
      "revised",
      "revising",
      "round of",
      "iteration",
      "rework",
      "change request",
      "additional work",
      "additional change",
      "additional charge",
      "additional fee",
      "extra work",
      "extra charge",
      "extra fee",
      "out of scope",
      "outside the scope",
      "outside scope",
      "beyond the scope",
      "beyond scope",
      "scope creep",
      "further change",
      "changes to the deliverable",
      "modifications to the deliverable",
    ],
    topicKeywords: [["revision"], ["rounds of"], ["change request"]],
  },
  {
    id: "acceptance",
    topic: "How work is accepted",
    explanation:
      "The agreement does not appear to say how or when delivered work is accepted. An acceptance clause, often with " +
      "a review period after which the work is treated as accepted, marks when the work is complete and payment " +
      "falls due.",
    presence: [
      "acceptance",
      "accept",
      "accepted",
      "accepting",
      "approve",
      "approved",
      "approval",
      "sign off",
      "signoff",
      "signed off",
      "review period",
      "reject",
      "rejected",
      "rejection",
      "satisfaction",
      "satisfactory",
    ],
    topicKeywords: [
      ["acceptance criteria"],
      ["acceptance process"],
      ["acceptance clause"],
      ["deemed accepted"],
      ["deemed acceptance"],
      ["sign off"],
      ["review period"],
    ],
  },
  {
    id: "termination",
    topic: "Termination and notice",
    explanation:
      "The agreement does not appear to say how either side can end it early, or with how much notice. Termination " +
      "terms set out how the engagement can end if the work or the relationship does not go as planned.",
    presence: [
      "terminate",
      "terminated",
      "terminating",
      "termination",
      "cancel",
      "cancelled",
      "canceled",
      "cancellation",
      "notice period",
      "end this agreement",
      "end the agreement",
      "discontinue",
      "rescind",
      "rescission",
    ],
    topicKeywords: [
      ["termination clause"],
      ["right to terminate"],
      ["termination right"],
      ["termination notice"],
      ["notice period"],
    ],
  },
  {
    id: "payment_on_termination",
    topic: "Payment for work done if the project ends early",
    explanation:
      "The agreement does not appear to say what is paid for work already done if the project is cancelled or " +
      "terminated early. A cancellation or kill fee, or pro-rata payment for completed work, covers the time " +
      "already spent.",
    presence: [
      "kill fee",
      "cancellation fee",
      "cancellation charge",
      "termination fee",
      "termination charge",
      "break fee",
      "work done",
      "work completed",
      "work performed",
      "work already",
      "services rendered",
      "services performed",
      "services delivered",
      "pro rata",
      "prorata",
      "pro rated",
      "prorated",
      "pro rate",
      "proportionate",
      "proportionately",
      "in proportion",
      "accrued",
      "date of termination",
      "work in progress",
      "up to the termination",
      "portion of the work",
      "partial work",
      "partially completed",
    ],
    topicKeywords: [["kill fee"], ["cancellation fee"], ["work done"], ["work completed"], ["pro rata"]],
  },
  {
    id: "liability_cap",
    topic: "Limit on liability",
    explanation:
      "The agreement does not appear to cap either side's liability. A limitation-of-liability clause, commonly " +
      "tied to the fees paid, bounds what either side can be asked to pay if something goes wrong.",
    presence: [
      "limitation of liability",
      "limitation on liability",
      "limit of liability",
      "limited liability",
      "liability shall be limited",
      "liability will be limited",
      "liability is limited",
      "liability limited",
      "aggregate liability",
      "total liability",
      "maximum liability",
      "entire liability",
      "cumulative liability",
      "cap on liability",
      "liability cap",
      "capped",
      "shall not exceed",
      "will not exceed",
      "in no event",
      "under no circumstances",
      "consequential",
      "indirect",
      "incidental",
      "special damages",
      "exemplary",
      "loss of profit",
      "lost profit",
    ],
    topicKeywords: [
      ["limitation of liability"],
      ["liability cap"],
      ["cap on liability"],
      ["limit", "liability"],
      ["unlimited liability"],
    ],
  },
  {
    id: "dispute_resolution",
    topic: "Dispute resolution",
    explanation:
      "The agreement does not appear to say how disputes will be resolved — negotiation, mediation, arbitration or " +
      "particular courts — or which law applies. Stating this avoids a separate argument about where and how a " +
      "dispute should be heard.",
    presence: [
      "governing law",
      "governed by",
      "construed in accordance",
      "law of india",
      "indian law",
      "jurisdiction",
      "court",
      "arbitration",
      "arbitrator",
      "arbitral",
      "mediation",
      "mediator",
      "conciliation",
      "dispute",
      "tribunal",
    ],
    topicKeywords: [["dispute resolution"], ["arbitration"], ["jurisdiction"], ["governing law"]],
  },
  {
    id: "taxes",
    topic: "Tax responsibility (TDS and GST)",
    explanation:
      "The agreement does not appear to say how tax is handled — whether fees include GST, and whether the client " +
      "will deduct TDS. This decides how much of the stated fee is actually received.",
    presence: [
      "tax",
      "taxation",
      "taxable",
      "tds",
      "withholding",
      "withhold",
      "gst",
      "igst",
      "cgst",
      "sgst",
      "gstin",
      "inclusive of",
      "exclusive of",
    ],
    topicKeywords: [["tds"], ["gst"], ["tax"], ["taxes"]],
  },
  {
    id: "confidentiality",
    topic: "Confidentiality",
    explanation:
      "The agreement does not appear to address confidentiality. Freelance agreements commonly say what information " +
      "each side must keep confidential, and for how long.",
    presence: [
      "confidential",
      "confidentiality",
      "non disclosure",
      "nondisclosure",
      "nda",
      "proprietary information",
      "trade secret",
      "secrecy",
    ],
    topicKeywords: [["confidentiality"], ["confidential"], ["non disclosure"]],
  },
];
