import type { StandardClauseItem } from "./types";

/** Standard protections in an Indian job offer or appointment letter. */
export const JOB_OFFER_LETTER_ITEMS: readonly StandardClauseItem[] = [
  {
    id: "probation",
    topic: "Probation and confirmation",
    explanation:
      "The letter does not appear to mention a probation period or how employment is confirmed. Offers in India " +
      "commonly state the probation length and the notice that applies during it, which often differs from the " +
      "notice after confirmation.",
    presence: [
      "probation",
      "probationary",
      "probationer",
      "trial period",
      "on trial",
      "confirmation of employment",
      "confirmation of your employment",
      "confirmation of service",
      "confirmation of your service",
      "confirmation period",
      "upon confirmation",
      "on confirmation",
      "after confirmation",
      "post confirmation",
      "confirmed in",
      "confirmed as",
      "confirmed employee",
    ],
    topicKeywords: [["probation"], ["probationary"]],
  },
  {
    id: "notice_period",
    topic: "Notice period",
    explanation:
      "The letter does not appear to state a notice period for resignation or termination. A stated notice period " +
      "says how much warning each side must give, and whether salary can be paid instead of notice.",
    presence: [
      "notice period",
      "period of notice",
      "month notice",
      "day notice",
      "week notice",
      "prior notice",
      "advance notice",
      "written notice",
      "notice in writing",
      "notice of resignation",
      "notice of termination",
      "resignation notice",
      "termination notice",
      "notice of 1",
      "notice of not less than",
      "notice of at least",
      "in lieu of notice",
      "in lieu of the notice",
      "salary in lieu",
      "pay in lieu",
      "payment in lieu",
      "notice pay",
      "buyout",
      "buy out",
      "serve notice",
      "serving notice",
      "served notice",
      "give notice",
      "giving notice",
    ],
    topicKeywords: [["notice period"], ["period of notice"]],
  },
  {
    id: "salary_breakup",
    topic: "Salary break-up",
    explanation:
      "The letter does not appear to break the pay down into its components, such as basic pay, allowances, " +
      "variable pay and employer contributions. Without a break-up, the monthly in-hand amount can differ from the " +
      "headline figure in ways that are hard to check.",
    presence: [
      "basic",
      "hra",
      "allowance",
      "break up",
      "breakup",
      "breakdown",
      "salary structure",
      "compensation structure",
      "pay structure",
      "component",
      "fixed pay",
      "variable pay",
      "performance bonus",
      "gross salary",
      "gross pay",
      "in hand",
      "take home",
      "net salary",
      "net pay",
      "annexure",
      "appendix",
    ],
    topicKeywords: [["break up"], ["breakup"], ["breakdown"], ["salary structure"], ["component"]],
  },
  {
    id: "working_hours",
    topic: "Working hours and weekly off",
    explanation:
      "The letter does not appear to state working hours or weekly days off. For many employees in India, working " +
      "hours and overtime are regulated by state shops-and-establishments laws, and stating the hours in writing " +
      "helps if expectations later differ.",
    presence: [
      "working hour",
      "work hour",
      "hours of work",
      "office hour",
      "working time",
      "timing",
      "hour per day",
      "hour a day",
      "hour per week",
      "hour a week",
      "hour each day",
      "work week",
      "working week",
      "working day",
      "workday",
      "weekly off",
      "week off",
      "weekly holiday",
      "day off",
      "shift",
      "overtime",
      "monday to friday",
      "monday to saturday",
      "monday through friday",
      "am to",
    ],
    topicKeywords: [["working hour"], ["work hour"], ["hours of work"], ["weekly off"]],
  },
  {
    id: "leave_entitlement",
    topic: "Leave and holidays",
    explanation:
      "The letter does not appear to mention paid leave or holidays. Leave is usually set out in the offer or in a " +
      "policy it refers to, and state shops-and-establishments laws set minimum leave for many employees.",
    presence: [
      "leave policy",
      "annual leave",
      "sick leave",
      "casual leave",
      "earned leave",
      "privilege leave",
      "paid leave",
      "leave entitlement",
      "leave encashment",
      "leave without pay",
      "leave balance",
      "leave rule",
      "leave per",
      "leave in a",
      "leave in each",
      "leave annually",
      "leave as per",
      "leave in accordance",
      "day of leave",
      "days leave",
      "12 leaves",
      "entitled to leave",
      "eligible for leave",
      "maternity",
      "paternity",
      "holiday",
      "vacation",
      "pto",
      "time off",
    ],
    topicKeywords: [["leave policy"], ["paid leave"], ["leave entitlement"], ["holiday"], ["annual leave"]],
  },
  {
    id: "termination_grounds",
    topic: "Grounds for termination",
    explanation:
      "The letter does not appear to say when or how the employer may end the employment. Offers commonly state the " +
      "grounds for termination, such as misconduct, and the notice or pay that applies, so it is clear how " +
      "employment can end.",
    presence: [
      "terminate",
      "terminated",
      "terminating",
      "termination",
      "dismiss",
      "dismissed",
      "dismissal",
      "discharge",
      "discharged",
      "misconduct",
      "cessation of employment",
      "separation",
      "end your employment",
      "end the employment",
      "end of employment",
    ],
    topicKeywords: [
      ["grounds for termination"],
      ["grounds of termination"],
      ["termination grounds"],
      ["reasons for termination"],
      ["dismissal"],
      ["misconduct"],
    ],
  },
  {
    id: "confidentiality",
    topic: "Confidentiality",
    explanation:
      "The letter does not appear to mention confidentiality. Offers commonly state what information must be kept " +
      "confidential and for how long, often by referring to a separate agreement or policy.",
    presence: [
      "confidential",
      "confidentiality",
      "non disclosure",
      "nondisclosure",
      "nda",
      "proprietary information",
      "trade secret",
      "secrecy",
    ],
    topicKeywords: [["confidentiality"], ["confidential"], ["non disclosure"]],
  },
  {
    id: "statutory_benefits",
    topic: "Provident fund, gratuity and insurance",
    explanation:
      "The letter does not appear to mention provident fund, gratuity, ESI or insurance. Where these laws apply to " +
      "the employer, the contributions are usually shown in the pay break-up, and they explain part of the gap " +
      "between the headline figure and in-hand pay.",
    presence: [
      "provident fund",
      "pf",
      "epf",
      "epfo",
      "gratuity",
      "esi",
      "esic",
      "insurance",
      "mediclaim",
      "medical cover",
      "health cover",
      "nps",
      "national pension",
      "superannuation",
      "benefit",
    ],
    topicKeywords: [["provident fund"], ["pf"], ["gratuity"], ["esi"], ["insurance"]],
  },
  {
    id: "place_of_work",
    topic: "Place of work and transfers",
    explanation:
      "The letter does not appear to state where the job is based or whether the employer can transfer the employee " +
      "elsewhere. A stated location, and any transfer clause, sets out whether relocation can be required later.",
    presence: [
      "location",
      "located",
      "place of work",
      "posting",
      "posted",
      "based at",
      "based in",
      "based out of",
      "office at",
      "work from home",
      "work from office",
      "remote",
      "remotely",
      "hybrid",
      "transfer",
      "transferred",
      "transferable",
      "relocate",
      "relocation",
      "relocated",
      "deputed",
      "deputation",
      "branch",
    ],
    topicKeywords: [["place of work"], ["work location"], ["job location"], ["transfer"], ["relocation"]],
  },
];
