import type { StandardClauseItem } from "./types";

/** Standard protections in an Indian leave-and-license or rent agreement. */
export const LEAVE_AND_LICENSE_ITEMS: readonly StandardClauseItem[] = [
  {
    id: "security_deposit_refund",
    topic: "Security deposit refund",
    explanation:
      "The agreement does not appear to say whether or when the security deposit is returned. Rental agreements " +
      "commonly set a refund timeline and state what may be deducted, which helps avoid disputes at move-out.",
    presence: [
      "refund",
      "refunded",
      "refundable",
      "refunding",
      "repay",
      "repaid",
      "repayable",
      "repayment",
      "return the deposit",
      "return the security deposit",
      "return of the deposit",
      "return of the security deposit",
      "return of deposit",
      "return of security deposit",
      "deposit is returned",
      "deposit returned",
      "shall be returned",
      "will be returned",
      "deposit back",
      "pay back",
      "paid back",
      "give back",
      "given back",
      "adjusted against",
    ],
    topicKeywords: [
      ["deposit", "refund"],
      ["deposit", "refunded"],
      ["deposit", "refundable"],
      ["deposit", "return"],
      ["deposit", "returned"],
      ["deposit", "returning"],
    ],
  },
  {
    id: "termination_notice",
    topic: "Notice period to end the agreement",
    explanation:
      "The agreement does not appear to set a notice period for ending it early. A notice period says how much " +
      "warning each side must give, so neither the tenant nor the landlord is caught out by a sudden end.",
    presence: [
      "notice period",
      "period of notice",
      "month notice",
      "day notice",
      "week notice",
      "prior notice",
      "advance notice",
      "written notice",
      "notice in writing",
      "notice of termination",
      "termination notice",
      "notice to terminate",
      "notice for termination",
      "notice to vacate",
      "notice of 1",
      "notice of not less than",
      "notice of at least",
      "notice of minimum",
      "giving notice",
      "give notice",
      "given notice",
      "serving notice",
      "serve notice",
      "served notice",
    ],
    topicKeywords: [["notice period"], ["period of notice"]],
  },
  {
    id: "rent_due_date",
    topic: "Rent due date",
    explanation:
      "The agreement does not appear to say when each month's rent is due. A fixed due date makes it clear when a " +
      "payment counts as late, which matters wherever the agreement charges for late payment or treats non-payment " +
      "as a breach.",
    presence: [
      "due date",
      "due on",
      "due by",
      "fall due",
      "payable on",
      "payable by",
      "payable within",
      "paid within",
      "in advance",
      "on or before",
      "of every month",
      "of each month",
      "of the month",
      "every calendar month",
      "each calendar month",
      "every english calendar month",
      "each english calendar month",
      "first week of",
      "first day of",
      "day of every",
      "day of each",
    ],
    topicKeywords: [["due date"], ["payment date"], ["rent", "is due"], ["rent", "falls due"]],
  },
  {
    id: "rent_escalation",
    topic: "Rent increase terms",
    explanation:
      "The agreement does not appear to say whether, or by how much, the rent can go up — for example on renewal. " +
      "Many rental agreements fix the increase in advance, often as a percentage, so both sides know what a renewal " +
      "will cost.",
    presence: [
      "escalation",
      "escalate",
      "escalated",
      "escalating",
      "increase",
      "increased",
      "increasing",
      "increment",
      "enhance",
      "enhanced",
      "enhancement",
      "hike",
      "revise",
      "revised",
      "revision",
      "percent",
      "per cent",
      "percentage",
      "remain fixed",
      "remain unchanged",
      "remain the same",
    ],
    topicKeywords: [
      ["escalation"],
      ["rent increase"],
      ["rent hike"],
      ["increase in rent"],
      ["increase in the rent"],
      ["rent revision"],
    ],
  },
  {
    id: "renewal",
    topic: "Renewal",
    explanation:
      "The agreement does not appear to say whether it can be renewed or extended when the term ends, or on what " +
      "terms. Without this, continuing after the term depends entirely on a fresh agreement between the parties.",
    presence: [
      "renew",
      "renewal",
      "renewed",
      "renewing",
      "renewable",
      "extend",
      "extended",
      "extension",
      "extending",
      "further period",
      "further term",
      "fresh agreement",
      "new agreement",
    ],
    topicKeywords: [
      ["renewal clause"],
      ["renewal option"],
      ["option to renew"],
      ["right to renew"],
      ["not renewable"],
    ],
  },
  {
    id: "maintenance_and_repairs",
    topic: "Maintenance and repairs",
    explanation:
      "The agreement does not appear to say who is responsible for maintenance and repairs. Rental agreements " +
      "commonly split this — minor day-to-day repairs to the tenant, structural or major repairs to the landlord — " +
      "so the cost of a breakdown is not disputed later.",
    presence: [
      "repair",
      "repaired",
      "repairing",
      "maintenance",
      "maintain",
      "maintained",
      "maintaining",
      "upkeep",
      "wear and tear",
      "structural",
      "fix",
      "fixing",
    ],
    topicKeywords: [
      ["repair", "responsible"],
      ["repair", "responsibility"],
      ["maintenance", "responsible"],
      ["maintenance", "responsibility"],
    ],
  },
  {
    id: "utilities_and_charges",
    topic: "Utility bills and society charges",
    explanation:
      "The agreement does not appear to say who pays electricity, water, gas or housing-society charges. Setting " +
      "this out avoids disagreement over bills that arrive during, or after, the stay.",
    presence: [
      "electricity",
      "electric",
      "water",
      "gas",
      "utility",
      "society charge",
      "society maintenance",
      "maintenance charge",
      "outgoings",
      "bill",
      "municipal tax",
      "property tax",
      "internet",
      "broadband",
    ],
    topicKeywords: [["utility"], ["electricity", "water"]],
  },
  {
    id: "registration_and_stamp_duty",
    topic: "Stamp duty and registration",
    explanation:
      "The agreement does not appear to mention stamp duty or registration. Rental agreements in India attract " +
      "stamp duty, and some must also be registered — leases for more than a year under the Registration Act, 1908, " +
      "and leave-and-license agreements in Maharashtra. An unstamped or unregistered agreement can be harder to rely " +
      "on as evidence.",
    presence: [
      "stamp",
      "stamped",
      "stamping",
      "estamp",
      "estamped",
      "registration",
      "registering",
      "registrar",
      "subregistrar",
      "registered with",
      "registered under",
      "registered before",
      "registered at",
      "duly registered",
      "be registered",
      "get registered",
      "got registered",
      "register this agreement",
      "register the agreement",
      "register these presents",
    ],
    topicKeywords: [["stamp duty"], ["stamp paper"], ["registration"], ["unregistered"], ["unstamped"]],
  },
  {
    id: "subletting",
    topic: "Subletting and transfer",
    explanation:
      "The agreement does not appear to say whether the premises may be sublet or the agreement transferred to " +
      "someone else. Rental agreements commonly address this so both sides know who may occupy the premises.",
    presence: [
      "sublet",
      "sub let",
      "subletting",
      "sub letting",
      "sublease",
      "sub lease",
      "subleasing",
      "sub leasing",
      "sublicense",
      "sub license",
      "sublicence",
      "sub licence",
      "sublicensing",
      "sub licensing",
      "subtenant",
      "sub tenant",
      "assign",
      "assigned",
      "assignment",
      "assignee",
      "part with possession",
      "part with the possession",
      "parting with possession",
      "parting with the possession",
      "transfer",
      "transferred",
      "transferable",
      "third party",
      "any other person",
    ],
    topicKeywords: [
      ["sublet"],
      ["sub let"],
      ["subletting"],
      ["sub letting"],
      ["sublease"],
      ["sub lease"],
      ["sublicense"],
      ["sub license"],
      ["sublicence"],
      ["sub licence"],
    ],
  },
  {
    id: "landlord_entry",
    topic: "Landlord's entry into the premises",
    explanation:
      "The agreement does not appear to say when the landlord may enter or inspect the premises. Rental agreements " +
      "commonly require reasonable prior notice and reasonable hours, balancing the right to inspect with the " +
      "occupant's privacy.",
    presence: [
      "inspect",
      "inspection",
      "inspecting",
      "entry",
      "enter the",
      "enter upon",
      "enter into the premises",
      "enter into the said",
      "access to the premises",
      "access to the said premises",
      "access to the flat",
      "access to the property",
      "access the premises",
      "visit the premises",
      "visit the said premises",
    ],
    topicKeywords: [["entry"], ["inspect"], ["inspection"], ["enter", "premises"]],
  },
  {
    id: "fixtures_inventory",
    topic: "List of fixtures and fittings",
    explanation:
      "The agreement does not appear to list the fixtures, fittings or furniture handed over with the premises, or " +
      "their condition. A signed list is the usual reference when deductions for damage or missing items are " +
      "discussed at the end of the agreement.",
    presence: [
      "inventory",
      "fixture",
      "fitting",
      "furniture",
      "furnishing",
      "furnished",
      "appliance",
      "list of item",
      "list of article",
      "condition of the premises",
      "condition of the said premises",
      "present condition",
      "same condition",
      "good condition",
    ],
    topicKeywords: [["inventory"], ["list of fixture"], ["list of item"], ["list of furniture"]],
  },
];
