import type { StandardClauseItem } from "./types";

/** Standard protections in a non-disclosure agreement under Indian law. */
export const NDA_ITEMS: readonly StandardClauseItem[] = [
  {
    id: "definition_of_confidential_information",
    topic: "Definition of confidential information",
    explanation:
      "The agreement does not appear to define what counts as confidential information. A clear definition sets " +
      "the limits of the obligation; without one, it can be unclear which information is covered.",
    presence: [
      "confidential information means",
      "confidential information includes",
      "confidential information refers",
      "confidential information shall refer",
      "confidential information is defined",
      "definition of confidential information",
      "defined as",
      "shall mean",
      "means any",
      "means all",
      "shall include",
      "including but not limited",
      "includes but is not limited",
      "including without limitation",
    ],
    topicKeywords: [
      ["definition", "confidential information"],
      ["define", "confidential information"],
      ["defined", "confidential information"],
    ],
  },
  {
    id: "exclusion_public_information",
    topic: "Exclusion for public information",
    explanation:
      "The agreement does not appear to exclude information that is already public, or becomes public without the " +
      "recipient's fault. This is a standard exclusion; without it, the obligation could cover information anyone " +
      "can find.",
    presence: [
      "public domain",
      "publicly available",
      "publicly known",
      "publicly accessible",
      "public knowledge",
      "available to the public",
      "known to the public",
      "generally available",
      "generally known",
      "become public",
      "made public",
      "is public",
      "already public",
      "public information",
    ],
    topicKeywords: [["public domain"], ["publicly available"], ["publicly known"], ["generally available"]],
  },
  {
    id: "exclusion_prior_or_third_party",
    topic: "Exclusion for information already known or received from others",
    explanation:
      "The agreement does not appear to exclude information the recipient already had, or lawfully received from " +
      "someone else who was free to share it. This standard exclusion keeps the obligation limited to what was " +
      "actually disclosed under the agreement.",
    presence: [
      "already known",
      "previously known",
      "known to the receiving party",
      "known to the recipient",
      "prior knowledge",
      "already in the possession",
      "already in possession",
      "already in its possession",
      "in the possession of the receiving party",
      "in the possession of the recipient",
      "rightfully received",
      "rightfully obtained",
      "rightfully known",
      "rightfully in",
      "lawfully received",
      "lawfully obtained",
      "lawfully known",
      "lawfully in",
      "from a third party",
      "from any third party",
      "without restriction",
      "without a duty of confidentiality",
      "without an obligation of confidentiality",
      "without any obligation of confidentiality",
    ],
    topicKeywords: [
      ["already known"],
      ["previously known"],
      ["prior knowledge"],
      ["already in", "possession"],
      ["rightfully"],
      ["lawfully", "third party"],
    ],
  },
  {
    id: "exclusion_independent_development",
    topic: "Exclusion for independently developed information",
    explanation:
      "The agreement does not appear to exclude information the recipient develops independently, without using the " +
      "disclosed information. This standard exclusion protects the recipient's own separate work.",
    presence: [
      "independently developed",
      "independently develop",
      "independently developing",
      "independent development",
      "developed independently",
      "develop independently",
      "independently created",
      "independently conceived",
      "independently generated",
      "independently derived",
      "independently acquired",
      "created independently",
      "without use of",
      "without the use of",
      "without reference to",
      "without any reference to",
    ],
    topicKeywords: [["independently"], ["independent development"]],
  },
  {
    id: "compelled_disclosure",
    topic: "Disclosure required by law",
    explanation:
      "The agreement does not appear to allow disclosure when a law, court or regulator requires it. Without this, " +
      "a recipient served with a legal order could be caught between the order and the agreement. Such clauses " +
      "usually ask for prompt notice to the other side first, where the law permits.",
    presence: [
      "required by law",
      "required by any law",
      "required by applicable law",
      "required under law",
      "required under any law",
      "required under applicable law",
      "required by statute",
      "requirement of law",
      "requirement of any law",
      "required by a court",
      "required by any court",
      "court order",
      "order of a court",
      "order of any court",
      "order of the court",
      "judicial order",
      "legal process",
      "subpoena",
      "summons",
      "regulatory authority",
      "governmental authority",
      "government authority",
      "statutory authority",
      "regulator",
      "law enforcement",
      "compelled",
      "compulsion of law",
      "operation of law",
      "mandated by law",
    ],
    topicKeywords: [
      ["required by law"],
      ["court order"],
      ["legal process"],
      ["compelled"],
      ["regulator"],
      ["required by", "court"],
    ],
  },
  {
    id: "duration_of_obligations",
    topic: "How long the confidentiality obligation lasts",
    explanation:
      "The agreement does not appear to say how long the confidentiality obligation lasts, or whether it continues " +
      "after the agreement ends. A stated duration tells the recipient when the obligation ends; without one, the " +
      "duration can itself become a dispute.",
    presence: [
      "year",
      "month",
      "survive",
      "surviving",
      "survival",
      "perpetual",
      "perpetually",
      "perpetuity",
      "indefinite",
      "indefinitely",
      "in force",
      "remain in effect",
      "remain effective",
      "continue in effect",
      "shall continue",
      "duration",
      "term of this agreement",
      "term of the agreement",
      "expiry",
      "expiration",
      "expire",
      "until",
      "after termination",
      "after the termination",
      "post termination",
      "following termination",
      "thereafter",
    ],
    topicKeywords: [["duration"], ["how long"], ["survive"], ["survival"]],
  },
  {
    id: "return_or_destruction",
    topic: "Return or destruction of information",
    explanation:
      "The agreement does not appear to require confidential material to be returned or destroyed when the " +
      "relationship ends or on request. Such a clause, often with a written confirmation, sets out what happens to " +
      "copies the recipient still holds.",
    presence: [
      "return",
      "returned",
      "returning",
      "destroy",
      "destroyed",
      "destroying",
      "destruction",
      "delete",
      "deleted",
      "deleting",
      "deletion",
      "erase",
      "erased",
      "erasure",
      "purge",
      "purged",
      "dispose",
      "disposed",
      "disposal",
      "shred",
    ],
    topicKeywords: [["return", "destroy"], ["return", "destruction"], ["returned", "destroyed"], ["destruction"]],
  },
  {
    id: "remedies",
    topic: "Remedies for breach",
    explanation:
      "The agreement does not appear to say what remedies are available if confidential information is misused, " +
      "such as an injunction or damages. Remedies may still be available under general law, but NDAs commonly " +
      "state them expressly, particularly the right to seek an injunction quickly.",
    presence: [
      "injunction",
      "injunctive",
      "specific performance",
      "damage",
      "remedy",
      "indemnify",
      "indemnified",
      "indemnity",
      "indemnification",
      "compensate",
      "compensation",
      "irreparable",
      "relief",
    ],
    topicKeywords: [["remedy"], ["injunction"], ["injunctive"]],
  },
  {
    id: "permitted_recipients",
    topic: "Who the recipient may share information with",
    explanation:
      "The agreement does not appear to say whether the recipient may share information with its employees, " +
      "advisers or affiliates on a need-to-know basis. Such a clause sets out who else may see the information, and " +
      "usually makes the recipient answerable for them.",
    presence: [
      "need to know",
      "employee",
      "officer",
      "director",
      "adviser",
      "advisor",
      "consultant",
      "representative",
      "affiliate",
      "agent",
      "contractor",
      "auditor",
      "lawyer",
      "counsel",
    ],
    topicKeywords: [["need to know"], ["representative"], ["affiliate"], ["employee", "share"]],
  },
  {
    id: "purpose_limitation",
    topic: "Limits on how the information may be used",
    explanation:
      "The agreement does not appear to limit the recipient's use of the information to a stated purpose. A purpose " +
      "clause keeps the information from being used for anything other than what the NDA was signed for.",
    presence: [
      "purpose",
      "solely for",
      "only for",
      "permitted use",
      "not use",
      "shall use",
      "use the confidential information",
      "use any confidential information",
      "use of the confidential information",
      "use of confidential information",
      "for any other",
    ],
    topicKeywords: [["permitted purpose"], ["purpose limitation"], ["stated purpose"], ["limit", "use"]],
  },
  {
    id: "governing_law_and_disputes",
    topic: "Governing law and dispute resolution",
    explanation:
      "The agreement does not appear to say which law governs it or how disputes are resolved — courts or " +
      "arbitration, and where. Stating this avoids a separate argument about where and how a dispute should be heard.",
    presence: [
      "governing law",
      "governed by",
      "construed in accordance",
      "law of india",
      "indian law",
      "jurisdiction",
      "court",
      "arbitration",
      "arbitrator",
      "arbitral",
      "mediation",
      "mediator",
      "conciliation",
      "dispute",
      "tribunal",
    ],
    topicKeywords: [["governing law"], ["jurisdiction"], ["dispute resolution"], ["arbitration"]],
  },
];
