import type { StandardClauseItem } from "./types";

/** Standard disclosures in a privacy policy under the Digital Personal Data Protection Act, 2023. */
export const PRIVACY_POLICY_ITEMS: readonly StandardClauseItem[] = [
  {
    id: "data_collected",
    topic: "What personal data is collected",
    explanation:
      "The policy does not appear to describe what personal data is collected. Under the Digital Personal Data " +
      "Protection Act, 2023, the notice given to an individual must describe the personal data to be processed.",
    presence: [
      "collect",
      "collected",
      "collecting",
      "collection",
      "gather",
      "gathered",
      "obtain",
      "obtained",
      "we receive",
      "information we",
      "data we",
      "you provide",
      "you give us",
      "you share",
    ],
    topicKeywords: [["what personal data"], ["what data"], ["categories of personal data"], ["types of data"]],
  },
  {
    id: "purposes_of_processing",
    topic: "Purposes of processing",
    explanation:
      "The policy does not appear to state why personal data is processed. Under the Digital Personal Data " +
      "Protection Act, 2023, the notice must state the purpose, and personal data may be processed only for a " +
      "lawful purpose.",
    presence: [
      "purpose",
      "we use",
      "use your",
      "use the",
      "use of your",
      "use this",
      "use such",
      "used to",
      "used for",
      "process your",
      "processed for",
      "processing for",
      "in order to",
    ],
    topicKeywords: [["purpose of processing"], ["purpose", "processed"], ["why", "data", "used"]],
  },
  {
    id: "consent_withdrawal",
    topic: "Withdrawing consent",
    explanation:
      "The policy does not appear to explain how to withdraw consent. The Digital Personal Data Protection Act, 2023 " +
      "lets an individual withdraw consent at any time, as easily as it was given.",
    presence: [
      "withdraw",
      "withdrawal",
      "withdrawn",
      "withdrawing",
      "revoke",
      "revoked",
      "revoking",
      "revocation",
      "opt out",
      "opting out",
      "opted out",
      "unsubscribe",
      "unsubscribing",
      "manage your consent",
      "consent manager",
      "change your consent",
      "change your preference",
      "manage your preference",
    ],
    topicKeywords: [["withdraw"], ["withdrawal"], ["withdrawing"], ["revoke"]],
  },
  {
    id: "sharing_and_processors",
    topic: "Sharing with third parties and processors",
    explanation:
      "The policy does not appear to say whether personal data is shared with anyone else, such as service providers " +
      "who process it on the company's behalf. Knowing who receives the data helps an individual decide whether to " +
      "share it.",
    presence: [
      "share",
      "shared",
      "sharing",
      "disclose",
      "disclosed",
      "disclosure",
      "third party",
      "processor",
      "service provider",
      "vendor",
      "partner",
      "affiliate",
      "transfer",
      "transferred",
      "sell",
      "sold",
      "on our behalf",
      "on its behalf",
    ],
    topicKeywords: [["processor"], ["service provider"], ["who", "shared"], ["sharing with"], ["share", "third party"]],
  },
  {
    id: "cross_border_transfer",
    topic: "Transfers outside India",
    explanation:
      "The policy does not appear to say whether personal data may be stored or processed outside India. The Digital " +
      "Personal Data Protection Act, 2023 allows the government to restrict transfers to particular countries, and " +
      "a policy usually states where data may go.",
    presence: [
      "outside india",
      "outside of india",
      "beyond india",
      "cross border",
      "abroad",
      "overseas",
      "other country",
      "another country",
      "any country",
      "foreign",
      "international transfer",
      "internationally",
      "outside the country",
      "outside your country",
      "other jurisdiction",
      "server located",
      "stored in",
      "hosted in",
      "data centre",
      "data center",
      "cloud",
      "globally",
      "worldwide",
    ],
    topicKeywords: [["outside india"], ["cross border"], ["abroad"], ["overseas"], ["other countries"]],
  },
  {
    id: "retention",
    topic: "How long data is kept",
    explanation:
      "The policy does not appear to say how long personal data is kept. Under the Digital Personal Data Protection " +
      "Act, 2023, personal data must generally be erased once its purpose is served, unless a law requires it to be " +
      "kept.",
    presence: [
      "retain",
      "retained",
      "retaining",
      "retention",
      "keep your",
      "keep personal",
      "keep the data",
      "kept for",
      "kept as long",
      "store your",
      "stored for",
      "as long as",
      "for as long",
      "no longer than",
      "longer than necessary",
      "longer than required",
      "period of time",
      "storage period",
      "archive",
      "archived",
    ],
    topicKeywords: [["retention"], ["retain"], ["how long", "kept"], ["how long", "stored"], ["how long", "keep"]],
  },
  {
    id: "security_and_breach",
    topic: "Security safeguards and breach notification",
    explanation:
      "The policy does not appear to describe how personal data is protected or what happens after a data breach. " +
      "The Digital Personal Data Protection Act, 2023 requires reasonable security safeguards, and notice of a " +
      "personal data breach to the Data Protection Board and to each affected individual.",
    presence: [
      "security",
      "secure",
      "secured",
      "securely",
      "safeguard",
      "encrypt",
      "encrypted",
      "encryption",
      "breach",
      "protect your",
      "protection of your",
      "protect personal",
      "protect the personal",
      "unauthorised access",
      "unauthorized access",
      "firewall",
      "access control",
    ],
    topicKeywords: [["security"], ["breach"], ["safeguard"]],
  },
  {
    id: "data_principal_rights",
    topic: "Rights to access, correct and erase data",
    explanation:
      "The policy does not appear to explain how an individual can access, correct or erase their personal data. " +
      "The Digital Personal Data Protection Act, 2023 gives individuals these rights.",
    presence: [
      "your right",
      "right to access",
      "right of access",
      "right to correct",
      "right to erase",
      "right to deletion",
      "right to delete",
      "right to update",
      "access your",
      "access to your",
      "correct your",
      "correction",
      "rectify",
      "rectification",
      "update your",
      "erase your",
      "erasure",
      "delete your",
      "deletion of your",
      "request deletion",
      "data principal right",
      "rights of the data principal",
      "rights of data principal",
      "rights under",
    ],
    topicKeywords: [
      ["access", "correct"],
      ["access", "erase"],
      ["correction", "erasure"],
      ["your right"],
      ["data principal right"],
    ],
  },
  {
    id: "nomination",
    topic: "Nominating someone to act for you",
    explanation:
      "The policy does not appear to mention nomination. The Digital Personal Data Protection Act, 2023 lets an " +
      "individual nominate another person to exercise their rights in the event of death or incapacity.",
    presence: ["nominate", "nominated", "nominating", "nomination", "nominee"],
    topicKeywords: [["nominate"], ["nomination"], ["nominee"]],
  },
  {
    id: "grievance_redressal",
    topic: "Grievance officer and complaints",
    explanation:
      "The policy does not appear to name a grievance officer or explain how to raise a complaint. The Digital " +
      "Personal Data Protection Act, 2023 requires a way to resolve grievances and published contact details for " +
      "someone who can answer questions about the processing.",
    presence: [
      "grievance",
      "redress",
      "redressal",
      "complaint",
      "complain",
      "data protection officer",
      "dpo",
      "nodal officer",
      "privacy officer",
      "data protection board",
      "ombudsman",
    ],
    topicKeywords: [["grievance"], ["complaint"], ["data protection officer"], ["redressal"]],
  },
  {
    id: "childrens_data",
    topic: "Children's data",
    explanation:
      "The policy does not appear to say how children's personal data is handled. Under the Digital Personal Data " +
      "Protection Act, 2023, processing the personal data of anyone under 18 generally needs verifiable consent " +
      "from a parent or lawful guardian.",
    presence: [
      "child",
      "children",
      "minor",
      "under 18",
      "under the age",
      "below 18",
      "below the age",
      "age of 18",
      "years of age",
      "parent",
      "parental",
      "guardian",
      "kid",
    ],
    topicKeywords: [["child"], ["children"], ["minor"], ["parental"]],
  },
  {
    id: "policy_changes",
    topic: "How changes to the policy are notified",
    explanation:
      "The policy does not appear to say how, or whether, users will be told when it changes. A stated process for " +
      "notifying changes lets users review new terms before they apply.",
    presence: [
      "change",
      "changed",
      "changing",
      "update",
      "updated",
      "updating",
      "amend",
      "amended",
      "amendment",
      "modify",
      "modified",
      "modification",
      "revise",
      "revised",
      "revision",
      "effective date",
      "effective from",
      "version",
    ],
    topicKeywords: [["changes to this policy"], ["changes to the policy"], ["policy changes"], ["notify", "change"]],
  },
];
