import { defineConfig } from "vitest/config";
import tsconfigPaths from "vite-tsconfig-paths";

// Vitest 5's per-project `extends: true` snapshots this file's own declared values — a CLI
// `--exclude` flag (as `npm run test:coverage`'s script passes for *.timing.test.ts) does not
// propagate into an already-resolved project's file matching the way it does for a single-project
// config (confirmed empirically: `vitest list --exclude '**/*.timing.test.ts' <that file>` still
// lists it once `projects` is in play, but lists nothing with `projects` removed). Reading the
// `--coverage` flag directly here, once, reproduces the documented exclusion (coverage
// instrumentation skews a timing assertion) without depending on that CLI-to-project merge at all.
const isCoverageRun = process.argv.includes("--coverage");

// PGlite's WASM init is slow (release-note-documented), hence the generous
// timeouts — a tight default here would make PGlite-backed integration
// tests (later lanes) flaky rather than actually failing.
export default defineConfig({
  plugins: [tsconfigPaths()],
  test: {
    exclude: ["node_modules/**", ".next/**", ".planning/**", ".superpowers/**", ".claude/**"],
    testTimeout: 30_000,
    hookTimeout: 30_000,
    // Vitest 5 dropped environmentMatchGlobs; a glob ending in .test.ts never matches .test.tsx; a
    // component test needs a DOM the node environment doesn't have. Two projects, not one config
    // with a broad include, so node-only suites (PGlite, the http guards) never pay jsdom's cost.
    projects: [
      {
        extends: true,
        test: {
          name: "node",
          environment: "node",
          include: ["tests/**/*.test.ts"],
          setupFiles: ["tests/setup/no-network.ts"],
          // Only set at all during a coverage run — an explicit key here, even set to the same
          // base list, is what this project actually uses instead of inheriting the root's;
          // omitting the key entirely for a plain `npm test` keeps that inheritance intact rather
          // than risking a merge that treats an explicit `undefined` as "override to nothing."
          ...(isCoverageRun
            ? { exclude: ["node_modules/**", ".next/**", ".planning/**", ".superpowers/**", ".claude/**", "**/*.timing.test.ts"] }
            : {}),
        },
      },
      {
        extends: true,
        test: {
          name: "jsdom",
          environment: "jsdom",
          // no-network.ts's own suite is re-run here too, unchanged, so the guard it tests is
          // proven under this environment as well, not just assumed to carry over from the node
          // project's run of the same file.
          include: ["tests/unit/**/*.test.tsx", "tests/setup/no-network.test.ts"],
          setupFiles: ["tests/setup/no-network.ts", "tests/setup/jsdom.ts"],
        },
      },
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "json-summary"],
      reportsDirectory: "coverage",
      include: ["src/**/*.{ts,tsx}"],
      // Route handlers are thin adapters — one call into a service/repository function, shaped by a
      // view function; the branching and error handling they delegate to is covered where it lives.
      // src/components/ui and use-mobile are vendored shadcn output, generated by its CLI, not
      // authored here: the components built on top of them carry the tests, so the primitives
      // would only dilute the measure. Anything authored under src/components is still counted.
      exclude: ["src/app/api/**/route.ts", "**/*.d.ts", "src/components/ui/**", "src/hooks/use-mobile.ts"],
      // ~2 points below the baseline measured by `npm run test:coverage` (lines 97.57%,
      // statements 96.75%, functions 99.04%, branches 92.91%), floored. `isCoverageRun` above is
      // the sole mechanism excluding **/*.timing.test.ts from a coverage run (see its own
      // comment) — v8 instrumentation alone pushes verify.timing's measured CPU past the bound it
      // asserts, even at low machine load. package.json's `test:coverage` script passes no
      // `--exclude` flag of its own: `projects` being in play is what makes a CLI `--exclude`
      // flag not propagate into project file matching at all, so that flag would do nothing here.
      thresholds: {
        lines: 95,
        statements: 94,
        functions: 97,
        branches: 90,
      },
    },
  },
});
