// Capture states for /drafts/new and /drafts/[id]. Every fixture below is
// context.route-fulfilled — the same technique tests/e2e/screens/06-draft.spec.ts already uses for
// its own page.route mocks — rather than built through several real round trips: what these
// screenshots need to show is a specific, exact response shape (a not-ready grounding document, a
// branched revision chain, a 503 on revise), which is far easier to hold steady this way than to
// coax out of the real LLM pipeline. The fake provider resets before every capture (runner.ts), so
// nothing here relies on state left over from an earlier capture in the same run.

import type { CaptureContext, StateRegistry } from "../types";

function draftFixture(overrides: Record<string, unknown> = {}) {
  return {
    id: "draft-1",
    title: "Leave and License Agreement (Rental) draft",
    documentType: "leave_and_license",
    mode: "from_scratch",
    groundingDocumentId: null,
    revisionNumber: 1,
    parentDraftId: null,
    createdAt: "2026-01-01T00:00:00.000Z",
    expiresAt: null,
    modelUsed: "gemini-2.5-flash",
    jurisdiction: "IN",
    groundingDocumentAvailable: null,
    promptVersion: "v1",
    content: "Body text for every section, joined.",
    sections: [
      { key: "disclaimer", heading: "About This Draft", provenance: "templated", content: "This is a DRAFT Leave and License Agreement, generated by an AI drafting assistant for informational and drafting-assistance purposes only. It is general information, not legal advice." },
      { key: "parties_and_premises", heading: "Parties and Premises", provenance: "ai_generated", content: "The Licensor, Mr. Sudhir Karandikar, and the Licensee, Ms. Ishita Bhardwaj, agree to the following premises at Sahyadri Vista, Kharghar, Navi Mumbai." },
      { key: "term_rent_and_deposit", heading: "Term, Rent and Security Deposit", provenance: "ai_generated", content: "The license term is eleven months from 1 October 2026, at a monthly rent of Rs. 32,000, with a refundable security deposit of Rs. 1,50,000." },
      { key: "termination_and_notice", heading: "Termination and Notice", provenance: "ai_generated", content: "Either party may terminate this Agreement on 30 days' prior written notice, subject to the lock-in period." },
      { key: "signatures", heading: "Signatures", provenance: "templated", content: "IN WITNESS WHEREOF, the parties have executed this Agreement.\n\nLICENSOR: ______________________\nLICENSEE: ______________________" },
    ],
    ...overrides,
  };
}

function documentDetailFixture(overrides: Record<string, unknown> = {}) {
  return {
    analysisState: "not_analyzed",
    document: {
      id: "doc-1",
      title: "Lease.pdf",
      sampleId: null,
      projectId: null,
      filename: "lease.pdf",
      mimeType: "application/pdf",
      processingStatus: "ready",
      inputMode: "text",
      documentType: "leave_and_license",
      jurisdiction: "IN",
      detectionConfidence: null,
      uploadedAt: "2026-01-01T00:00:00.000Z",
      expiresAt: null,
      ...(overrides.document as Record<string, unknown> | undefined),
    },
    analysis: null,
    findings: null,
  };
}

function revisionsFixture(items: Record<string, unknown>[]) {
  return { items };
}

async function routeJson(ctx: CaptureContext, glob: string, body: unknown): Promise<void> {
  await ctx.context.route(glob, (route) => route.fulfill({ json: body }));
}

async function routeStatus(ctx: CaptureContext, glob: string, status: number, body: unknown): Promise<void> {
  await ctx.context.route(glob, (route) => route.fulfill({ status, json: body }));
}

// Clicks the phone-only "Revisions (N)" sheet trigger when present, leaving desktop's own inline
// list (which has no such trigger) untouched — the same state serves both viewports' captures.
async function openPhoneRevisionsSheetIfPresent(ctx: CaptureContext): Promise<void> {
  const trigger = ctx.page.getByRole("button", { name: /^Revisions \(\d+\)$/ });
  if (await trigger.count()) {
    await trigger.click();
    await ctx.page.getByRole("dialog").waitFor({ state: "visible" });
  }
}

export const states: StateRegistry = {
  "new-empty": {
    route: "/drafts/new",
    async setup(ctx) {
      await routeJson(ctx, "**/api/documents?**", { items: [], nextCursor: null });
    },
  },

  "new-grounded-preselected": {
    route: "/drafts/new?grounding=doc-1",
    async setup(ctx) {
      await routeJson(ctx, "**/api/documents/doc-1", documentDetailFixture());
      await routeJson(ctx, "**/api/documents?**", { items: [{ id: "doc-1", title: "Lease.pdf", filename: "lease.pdf", documentType: "leave_and_license", processingStatus: "ready", analysisState: "not_analyzed", inputMode: "text", sampleId: null, projectId: null, uploadedAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", expiresAt: null }], nextCursor: null });
    },
  },

  "new-grounding-not-ready": {
    route: "/drafts/new?grounding=doc-pending",
    async setup(ctx) {
      await routeJson(ctx, "**/api/documents/doc-pending", documentDetailFixture({ document: { id: "doc-pending", processingStatus: "pending" } }));
      await routeJson(ctx, "**/api/documents?**", { items: [], nextCursor: null });
    },
  },

  "draft-default": {
    route: "/drafts/draft-1",
    async setup(ctx) {
      await routeJson(ctx, "**/api/drafts/draft-1", draftFixture());
      await routeJson(
        ctx,
        "**/api/drafts/draft-1/revisions",
        revisionsFixture([
          { id: "draft-1", parentDraftId: null, revisionNumber: 1, createdAt: "2026-01-01T00:00:00.000Z", modelUsed: "gemini-2.5-flash", userInstructions: "Draft a lease for a 1BHK in Kharghar", isCurrent: true, isLatest: true },
        ]),
      );
    },
  },

  "draft-revisions-branch": {
    route: "/drafts/rev-3",
    async setup(ctx) {
      const chain = [
        { id: "rev-1", parentDraftId: null, revisionNumber: 1, createdAt: "2026-01-01T00:00:00.000Z", modelUsed: "gemini-2.5-flash", userInstructions: "Draft a lease for a 1BHK in Kharghar", isCurrent: false, isLatest: false },
        { id: "rev-2", parentDraftId: "rev-1", revisionNumber: 2, createdAt: "2026-01-02T00:00:00.000Z", modelUsed: "gemini-2.5-flash", userInstructions: null, isCurrent: false, isLatest: false },
        { id: "rev-3", parentDraftId: "rev-1", revisionNumber: 2, createdAt: "2026-01-03T00:00:00.000Z", modelUsed: "gemini-3.5-flash-lite", userInstructions: "Shorten the notice period to 30 days", isCurrent: true, isLatest: true },
      ];
      await routeJson(ctx, "**/api/drafts/rev-3", draftFixture({ id: "rev-3", revisionNumber: 2, parentDraftId: "rev-1" }));
      await routeJson(ctx, "**/api/drafts/rev-3/revisions", revisionsFixture(chain));
    },
    async ready(ctx) {
      await ctx.page.waitForLoadState("networkidle");
      await openPhoneRevisionsSheetIfPresent(ctx);
    },
  },

  "draft-grounding-gone": {
    route: "/drafts/draft-1",
    async setup(ctx) {
      await routeJson(ctx, "**/api/drafts/draft-1", draftFixture({ mode: "document_grounded", groundingDocumentId: "doc-1", groundingDocumentAvailable: false }));
      await routeJson(
        ctx,
        "**/api/drafts/draft-1/revisions",
        revisionsFixture([
          { id: "draft-1", parentDraftId: null, revisionNumber: 1, createdAt: "2026-01-01T00:00:00.000Z", modelUsed: "gemini-2.5-flash", userInstructions: "Reply agreeing to the extension", isCurrent: true, isLatest: true },
        ]),
      );
    },
  },

  "draft-503": {
    route: "/drafts/draft-1",
    async setup(ctx) {
      await routeJson(ctx, "**/api/drafts/draft-1", draftFixture());
      await routeJson(
        ctx,
        "**/api/drafts/draft-1/revisions",
        revisionsFixture([
          { id: "draft-1", parentDraftId: null, revisionNumber: 1, createdAt: "2026-01-01T00:00:00.000Z", modelUsed: "gemini-2.5-flash", userInstructions: "Draft a lease for a 1BHK in Kharghar", isCurrent: true, isLatest: true },
        ]),
      );
      await routeStatus(ctx, "**/api/drafts/draft-1/revise", 503, {
        error: { code: "UPSTREAM_UNAVAILABLE", message: "The AI providers are busy right now. Try again in a few minutes." },
      });
    },
    async ready(ctx) {
      await ctx.page.waitForLoadState("networkidle");
      await ctx.page.getByLabel("Revise this draft").fill("Shorten the notice period further");
      await ctx.page.getByRole("button", { name: "Revise" }).click();
      await ctx.page.getByRole("note").filter({ hasText: "The AI providers are busy right now." }).waitFor({ state: "visible" });
    },
  },

  "export-menu-open": {
    route: "/drafts/draft-1",
    async setup(ctx) {
      await routeJson(ctx, "**/api/drafts/draft-1", draftFixture());
      await routeJson(
        ctx,
        "**/api/drafts/draft-1/revisions",
        revisionsFixture([
          { id: "draft-1", parentDraftId: null, revisionNumber: 1, createdAt: "2026-01-01T00:00:00.000Z", modelUsed: "gemini-2.5-flash", userInstructions: "Draft a lease for a 1BHK in Kharghar", isCurrent: true, isLatest: true },
        ]),
      );
    },
    async ready(ctx) {
      await ctx.page.waitForLoadState("networkidle");
      await ctx.page.getByRole("button", { name: "Export" }).click();
      await ctx.page.getByRole("menuitem", { name: "Download" }).waitFor({ state: "visible" });
    },
  },

  "phone-timeline": {
    route: "/drafts/rev-2",
    async setup(ctx) {
      const chain = [
        { id: "rev-1", parentDraftId: null, revisionNumber: 1, createdAt: "2026-01-01T00:00:00.000Z", modelUsed: "gemini-2.5-flash", userInstructions: "Draft a lease for a 1BHK in Kharghar", isCurrent: false, isLatest: false },
        { id: "rev-2", parentDraftId: "rev-1", revisionNumber: 2, createdAt: "2026-01-02T00:00:00.000Z", modelUsed: "gemini-2.5-flash", userInstructions: "Shorten the notice period to 30 days", isCurrent: true, isLatest: true },
      ];
      await routeJson(ctx, "**/api/drafts/rev-2", draftFixture({ id: "rev-2", revisionNumber: 2, parentDraftId: "rev-1" }));
      await routeJson(ctx, "**/api/drafts/rev-2/revisions", revisionsFixture(chain));
    },
    async ready(ctx) {
      await ctx.page.waitForLoadState("networkidle");
      await openPhoneRevisionsSheetIfPresent(ctx);
    },
  },
};
