/**
 * The single source of truth for draft skeletons: a `templated` section's body is fixed boilerplate
 * written here (the model never produces it); an `ai_generated` section's body comes from one LLM
 * call in services/draft.ts, keyed by `section.key`.
 */

import { AppError } from "../../core/errors";
import { DOCUMENT_TYPE_REGISTRY } from "../document-type-registry";
import type { DraftProvenance, DraftSectionTemplate, DraftTemplate } from "./types";

/**
 * The 6 draftable ids: the 5 deeply-tuned document types plus the `grounded_response` drafting
 * category. `generic` is excluded — it has no `draftTemplateRef` in the registry, existing only as
 * Understand's auto-detection fallback.
 */
export const DRAFTABLE_DOCUMENT_TYPE_IDS = [
  "leave_and_license",
  "job_offer_letter",
  "nda",
  "privacy_policy",
  "freelance_service_agreement",
  "grounded_response",
] as const;

/** One of {@link DRAFTABLE_DOCUMENT_TYPE_IDS}. */
export type DraftableDocumentTypeId = (typeof DRAFTABLE_DOCUMENT_TYPE_IDS)[number];

const TEMPLATED: DraftProvenance = "templated";
const AI_GENERATED: DraftProvenance = "ai_generated";

// Shared opener, reused verbatim by every template's first section — never generated by the model,
// since this is the section that tells the reader no draft here carries a verified badge.
function disclaimerBody(documentLabel: string): string {
  return (
    `This is a DRAFT ${documentLabel}, generated by an AI drafting assistant for informational and ` +
    "drafting-assistance purposes only. It is general information, not legal advice, and using it " +
    "does not create a lawyer-client relationship. Read it carefully and have it reviewed by a " +
    "qualified advocate before you sign, send, or rely on it for any legal or financial decision. " +
    "Depending on the document and the state, Indian law may require additional formalities — for " +
    "example stamp duty, registration, witnesses, or notarisation — that this draft does not by " +
    "itself satisfy."
  );
}

// Shared guidance for the governing-law/dispute-forum clause every contract template carries: an
// open choice between courts and arbitration is an ambiguous forum clause, so the model must commit
// to exactly one, not describe both as options.
function governingLawAndDisputesGuidance(partyVoice: string): string {
  return (
    `Write the operative clause text itself, ${partyVoice} voice: state that this Agreement is governed by Indian law, and name exactly one dispute ` +
    "forum — either the courts at a named Indian city, or arbitration under the Arbitration and Conciliation Act, 1996 with a named seat in India. Never " +
    'leave the choice open between the two. Use the city/seat the user\'s instructions or the grounding document gives; otherwise use a clear placeholder such as "[city]". No commentary.'
  );
}

// No section is guaranteed to state a date (any date comes from an ai_generated section, whose
// content isn't guaranteed) — each signatory's own "Date: __________" blank is the only date this
// document actually commits to.
function twoPartySignatureBlock(partyA: string, partyB: string): string {
  return (
    "IN WITNESS WHEREOF, the parties have executed this Agreement.\n\n" +
    `${partyA}: ______________________   Name: ______________________   Date: __________\n` +
    `${partyB}: ______________________   Name: ______________________   Date: __________\n\n` +
    "WITNESS 1: ______________________   WITNESS 2: ______________________"
  );
}

const leaveAndLicense: DraftSectionTemplate[] = [
  { key: "disclaimer", heading: "About This Draft", provenance: TEMPLATED, body: disclaimerBody("Leave and License Agreement") },
  {
    key: "parties_and_premises",
    heading: "Parties and Premises",
    provenance: AI_GENERATED,
    guidance:
      "Write the operative clause text itself, in the agreement's own voice using the defined terms LICENSOR and LICENSEE: name the parties and describe the licensed premises. No commentary about the clause.",
  },
  {
    key: "term_rent_and_deposit",
    heading: "Term, Rent and Security Deposit",
    provenance: AI_GENERATED,
    guidance: "Write the operative clause text itself, LICENSOR/LICENSEE voice: state the license term, monthly rent, and security deposit. No commentary.",
  },
  {
    key: "termination_and_notice",
    heading: "Termination and Notice",
    provenance: AI_GENERATED,
    guidance: "Write the operative clause text itself, LICENSOR/LICENSEE voice: state the notice period and the process for termination. No commentary.",
  },
  {
    key: "maintenance_and_restrictions",
    heading: "Maintenance, Utilities and Use Restrictions",
    provenance: AI_GENERATED,
    guidance:
      "Write the operative clause text itself, LICENSOR/LICENSEE voice: state maintenance responsibilities, utility payments, and use restrictions. No commentary.",
  },
  {
    key: "governing_law_and_disputes",
    heading: "Governing Law and Disputes",
    provenance: AI_GENERATED,
    guidance: governingLawAndDisputesGuidance("LICENSOR/LICENSEE"),
  },
  { key: "signatures", heading: "Signatures", provenance: TEMPLATED, body: twoPartySignatureBlock("LICENSOR", "LICENSEE") },
];

const jobOfferLetter: DraftSectionTemplate[] = [
  { key: "disclaimer", heading: "About This Draft", provenance: TEMPLATED, body: disclaimerBody("Job Offer Letter") },
  {
    key: "position_and_compensation",
    heading: "Position and Compensation",
    provenance: AI_GENERATED,
    guidance:
      'Write this as part of the offer letter itself, addressed to the candidate as "you", the company as "we"/"the Company": state the job title and compensation as operative terms. No commentary describing the letter.',
  },
  {
    key: "joining_and_probation",
    heading: "Date of Joining and Probation",
    provenance: AI_GENERATED,
    guidance: 'Write this as part of the offer letter itself, addressed to the candidate as "you": state the date of joining and probation period as operative terms. No commentary.',
  },
  {
    key: "notice_period_and_termination",
    heading: "Notice Period and Termination",
    provenance: AI_GENERATED,
    guidance: 'Write this as part of the offer letter itself, addressed to the candidate as "you": state the notice period and termination terms as operative terms. No commentary.',
  },
  {
    key: "other_terms",
    heading: "Other Terms of Employment",
    provenance: AI_GENERATED,
    guidance: 'Write this as part of the offer letter itself, addressed to the candidate as "you": state any other terms of employment as operative terms. No commentary.',
  },
  {
    key: "acceptance",
    heading: "Acceptance",
    provenance: TEMPLATED,
    body:
      "I have read and accepted the terms of this offer.\n\n" +
      "CANDIDATE SIGNATURE: ______________________   Name: ______________________   Date: __________\n" +
      "FOR THE COMPANY: ______________________   Name: ______________________   Designation: ______________________",
  },
];

const nda: DraftSectionTemplate[] = [
  { key: "disclaimer", heading: "About This Draft", provenance: TEMPLATED, body: disclaimerBody("Non-Disclosure Agreement") },
  {
    key: "parties_and_purpose",
    heading: "Parties and Purpose",
    provenance: AI_GENERATED,
    guidance: "Write the operative clause text itself, PARTY A/PARTY B voice: name the parties and state the purpose of disclosure. No commentary.",
  },
  {
    key: "confidential_information",
    heading: "Confidential Information",
    provenance: AI_GENERATED,
    guidance: "Write the operative clause text itself, PARTY A/PARTY B voice: define what counts as confidential information. No commentary.",
  },
  {
    key: "obligations_and_exclusions",
    heading: "Obligations and Exclusions",
    provenance: AI_GENERATED,
    guidance:
      "Write the operative clause text itself, PARTY A/PARTY B voice: state the receiving party's obligations and any exclusions from confidentiality. No commentary.",
  },
  {
    key: "term_and_remedies",
    heading: "Term and Remedies",
    provenance: AI_GENERATED,
    guidance: "Write the operative clause text itself, PARTY A/PARTY B voice: state the agreement's term and the remedies available for breach. No commentary.",
  },
  {
    key: "governing_law_and_disputes",
    heading: "Governing Law and Disputes",
    provenance: AI_GENERATED,
    guidance: governingLawAndDisputesGuidance("PARTY A/PARTY B"),
  },
  { key: "signatures", heading: "Signatures", provenance: TEMPLATED, body: twoPartySignatureBlock("PARTY A", "PARTY B") },
];

const privacyPolicy: DraftSectionTemplate[] = [
  { key: "disclaimer", heading: "About This Draft", provenance: TEMPLATED, body: disclaimerBody("Privacy Policy") },
  {
    key: "data_collected_and_purpose",
    heading: "Data Collected and Purpose of Processing",
    provenance: AI_GENERATED,
    guidance: 'Write this as policy text addressed to the user as "you", the operator as "we": state what data is collected and why. No commentary about the policy.',
  },
  {
    key: "sharing_and_transfers",
    heading: "Sharing and Cross-Border Transfers",
    provenance: AI_GENERATED,
    guidance: 'Write this as policy text, "we"/"you" voice: state who data is shared with and any cross-border transfers. No commentary.',
  },
  {
    key: "retention_and_rights",
    heading: "Retention and Your Rights under the DPDP Act, 2023",
    provenance: AI_GENERATED,
    guidance: 'Write this as policy text, "we"/"you" voice: state how long data is retained and the user\'s rights under the DPDP Act, 2023. No commentary.',
  },
  {
    key: "grievance_officer",
    heading: "Grievance Officer and Contact",
    provenance: AI_GENERATED,
    guidance: 'Write this as policy text, "we"/"you" voice: state how to contact the grievance officer. No commentary.',
  },
  {
    key: "effective_date",
    heading: "Effective Date and Changes to This Policy",
    provenance: TEMPLATED,
    // "Continued use constitutes acceptance" is deemed/implied consent — section 6(1) of the Digital
    // Personal Data Protection Act, 2023 requires consent through a clear affirmative action, so this
    // template never asserts that mere continued use supplies it.
    body:
      "This policy is effective from the date it is published and may be updated from time to time. " +
      "Material changes will be notified through the same channel this policy is published on. " +
      "Continuing to use the product or service does not itself constitute consent to a change that " +
      "affects how personal data is processed. Where the Digital Personal Data Protection Act, 2023 " +
      "requires consent, it will be sought again through a clear affirmative action, and can be " +
      "withdrawn as easily as it was given.",
  },
];

const freelanceServiceAgreement: DraftSectionTemplate[] = [
  { key: "disclaimer", heading: "About This Draft", provenance: TEMPLATED, body: disclaimerBody("Freelance Service Agreement") },
  {
    key: "parties_and_scope",
    heading: "Parties and Scope of Work",
    provenance: AI_GENERATED,
    guidance: "Write the operative clause text itself, CLIENT/FREELANCER voice: name the parties and describe the scope of work. No commentary.",
  },
  {
    key: "fees_and_payment",
    heading: "Fees, Milestones and Payment",
    provenance: AI_GENERATED,
    guidance: "Write the operative clause text itself, CLIENT/FREELANCER voice: state fees, milestones, and payment terms. No commentary.",
  },
  {
    key: "ip_and_confidentiality",
    heading: "Intellectual Property and Confidentiality",
    provenance: AI_GENERATED,
    guidance: "Write the operative clause text itself, CLIENT/FREELANCER voice: state intellectual property ownership and confidentiality obligations. No commentary.",
  },
  {
    key: "termination_and_liability",
    heading: "Termination and Liability",
    provenance: AI_GENERATED,
    guidance:
      "Write the operative clause text itself, CLIENT/FREELANCER voice: state termination terms; a mutual liability cap, with carve-outs for fraud, " +
      "wilful misconduct, and fees already due (unpaid fees are never capped); and an indemnity limited to third-party intellectual-property-infringement " +
      "claims, mutual and capped. No commentary.",
  },
  {
    key: "governing_law_and_disputes",
    heading: "Governing Law and Disputes",
    provenance: AI_GENERATED,
    guidance: governingLawAndDisputesGuidance("CLIENT/FREELANCER"),
  },
  { key: "signatures", heading: "Signatures", provenance: TEMPLATED, body: twoPartySignatureBlock("CLIENT", "FREELANCER") },
];

const groundedResponse: DraftSectionTemplate[] = [
  { key: "disclaimer", heading: "About This Draft", provenance: TEMPLATED, body: disclaimerBody("Response") },
  {
    key: "summary_of_what_you_received",
    heading: "Summary of What You Received",
    provenance: AI_GENERATED,
    guidance:
      'Write a short summary addressed to the user as "you" ("you received..."), describing what the document/notice/email was and its key points. This section describes; it is not the reply itself.',
  },
  {
    key: "your_response",
    heading: "Your Response",
    provenance: AI_GENERATED,
    guidance:
      "Write the reply itself, ready to send: first person, addressed to the other party by name if known, with a greeting, the request and its reasons, and no description of the email. Do not add your own closing or signature — the Closing section supplies it.",
  },
  {
    key: "next_steps",
    heading: "Suggested Next Steps",
    provenance: AI_GENERATED,
    guidance:
      'Write practical next steps as advice to the user, addressed as "you" ("you should..."). This is guidance for the user, not part of the reply being sent.',
  },
  {
    key: "closing",
    heading: "Closing",
    provenance: TEMPLATED,
    body: "Sincerely,\n\n______________________\nName: __________________________   Date: __________",
  },
];

/** Every draftable document type's template, keyed by id. */
export const DRAFT_TEMPLATES: Record<DraftableDocumentTypeId, DraftTemplate> = {
  leave_and_license: { documentType: "leave_and_license", sections: leaveAndLicense },
  job_offer_letter: { documentType: "job_offer_letter", sections: jobOfferLetter },
  nda: { documentType: "nda", sections: nda },
  privacy_policy: { documentType: "privacy_policy", sections: privacyPolicy },
  freelance_service_agreement: { documentType: "freelance_service_agreement", sections: freelanceServiceAgreement },
  grounded_response: { documentType: "grounded_response", sections: groundedResponse },
};

/** Whether `value` is one of {@link DRAFTABLE_DOCUMENT_TYPE_IDS}. */
export function isDraftableDocumentType(value: string): value is DraftableDocumentTypeId {
  return (DRAFTABLE_DOCUMENT_TYPE_IDS as readonly string[]).includes(value);
}

/**
 * Looks up a document type's draft template.
 * @throws AppError VALIDATION_FAILED when `documentType` isn't draftable — a caller input error,
 * not a server fault; services/draft.ts validates this earlier, so this is a defensive backstop.
 */
export function getDraftTemplate(documentType: string): DraftTemplate {
  if (!isDraftableDocumentType(documentType)) {
    throw new AppError("VALIDATION_FAILED", `No draft template exists for document type "${documentType}".`);
  }
  return DRAFT_TEMPLATES[documentType];
}

/** Every section key a document type's template requires, in template order. */
export function requiredSectionKeys(documentType: DraftableDocumentTypeId): string[] {
  return DRAFT_TEMPLATES[documentType].sections.map((section) => section.key);
}

/** The section keys of a document type's template whose body the model generates. */
export function aiSectionKeys(documentType: DraftableDocumentTypeId): string[] {
  return DRAFT_TEMPLATES[documentType].sections
    .filter((section) => section.provenance === "ai_generated")
    .map((section) => section.key);
}

/**
 * Every required section key missing from `sections`. A blank/whitespace-only body counts as
 * missing, the same as an absent one.
 */
export function missingRequiredSections(
  documentType: DraftableDocumentTypeId,
  sections: readonly { sectionKey: string; content: string }[],
): string[] {
  const nonBlank = new Set(sections.filter((section) => section.content.trim().length > 0).map((section) => section.sectionKey));
  return requiredSectionKeys(documentType).filter((key) => !nonBlank.has(key));
}

/** The heading for a section key, or the key itself if it isn't in the document type's template. */
export function headingFor(documentType: DraftableDocumentTypeId, sectionKey: string): string {
  return DRAFT_TEMPLATES[documentType].sections.find((section) => section.key === sectionKey)?.heading ?? sectionKey;
}

/**
 * Renders a completed draft's full text as Markdown, in the template's own section order (see
 * {@link DraftTemplate}). Every heading in it is a template's: an ai_generated body is escaped so it
 * can neither open a heading nor a code fence that would swallow the headings after it.
 */
export function renderDraftContent(documentType: DraftableDocumentTypeId, sections: { sectionKey: string; content: string }[]): string {
  const bySectionKey = new Map(sections.map((section) => [section.sectionKey, section.content]));
  const template = DRAFT_TEMPLATES[documentType];
  return template.sections
    .map((section) => {
      const body = bySectionKey.get(section.key) ?? "";
      return `## ${section.heading}\n\n${section.provenance === "ai_generated" ? neutralizeMarkdownStructure(body) : body}`;
    })
    .join("\n\n");
}

// Line endings are normalized first: CommonMark also ends a line at a lone "\r", which a split on
// "\n" alone would miss. Every "#" is escaped, and so is every "=" or "-" on a line holding nothing
// else but whitespace and ">" — so no ATX or setext heading can form, inside a list or blockquote
// either. A run of three backticks or tildes loses its first character to an escape, so it cannot
// open a fence. The patterns are linear: the text is model-controlled.
function neutralizeMarkdownStructure(body: string): string {
  return body
    .replace(/\r\n?/g, "\n")
    .replace(/#/g, "\\#")
    .replace(/`{3,}|~{3,}/g, (run) => `\\${run}`)
    .split("\n")
    .map((line) => (/[=-]/.test(line) && !/[^\s>=-]/.test(line) ? line.replace(/[=-]/g, "\\$&") : line))
    .join("\n");
}

/**
 * Every document-type-registry entry with a `draftTemplateRef` — must match
 * {@link DRAFT_TEMPLATES}'s keys exactly.
 */
export const REGISTRY_DRAFTABLE_IDS = DOCUMENT_TYPE_REGISTRY.filter((entry) => entry.draftTemplateRef !== undefined).map(
  (entry) => entry.id,
);
